export const key = {
	public_key: `-----BEGIN PUBLIC KEY-----
	MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJV0ro/+qfl1IqZD6rPeW35gimlsjKgg
	skdQ9wS/CzAI5fz7tufvYGag9sPbvsy7gXVDbLXxOQaXygVPHpm2QjECAwEAAQ==
	-----END PUBLIC KEY-----`,
	private_key: `-----BEGIN RSA PRIVATE KEY-----
	MIIBOwIBAAJBAJV0ro/+qfl1IqZD6rPeW35gimlsjKggskdQ9wS/CzAI5fz7tufv
	YGag9sPbvsy7gXVDbLXxOQaXygVPHpm2QjECAwEAAQJARc7JVmK529XViFmCv97l
	V2MaY2GbVVBoVR1BM8tUG2vlwVNKhKzs9O8TU6f4TUBQ8PLjtIKsENQYPLN81djC
	0QIhAMqjKxPnhYgCjT0znv6FXS4iLx64JZMUDCHs4AvyLQkdAiEAvNBEqphy/1r4
	Lux6kh8akRmPWjtCrJEXDxzX7p+x5SUCIQCwNqp8WaY+O3HVWfGWhiUcvC9buGk8
	eH+AdPv0h3nwZQIgAOqJysIenLqWRbQEDD12ZYnYNjnfYvL5R6t+KLxBorkCIQDC
	415SIOzSZwNz/7JXsZs9tjISAfApXCbNyTHjPIg6KQ==
	-----END RSA PRIVATE KEY-----`
};
